### ISSUE TITLE
probable bug in src/utils/file_utils.py

### ISSUE THREAD

**Issue by bashirulazam** [deeplab-ai/atr-net#1]
I have been trying to run your code for sometime. But I was having error while loading the dataset. I changed line 34 of src/utils/file_utils.py as follows.

34:  orig_img_names = set(os.listdir(ORIG_IMAGES_PATH[dataset]))

Previously it was ORIG_ANNOS_PATHS and the annotations variables was being null. 

Now the training is going on. You might want to look into this issue.

**Comment by nickgkan** [comment]
Hi @bashirulazam 
Yes you are right, that was due to an incorrect copy-paste while cleaning the code. Fixed it!

Thanks for the interest in our work!
