### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'json_annos/VG200_sggen.json'

### ISSUE THREAD

**Issue by Nimo1989** [deeplab-ai/atr-net#5]
First, thanks for your code. I want to train a model use the code as follow:

python3 main.py --dataset=VG200 --task=sggen --model=atr_net.

But, I got the error:

load checkpoint faster_rcnn/faster_rcnn_1_10_14657.pth
Tackling sggen for 51 classes
{'attention': 'multi_head', 'use_language': True, 'use_spatial': True}
2021-07-08 21:47:58,190 - DEBUG - Tackling sggen for 51 classes
load checkpoint faster_rcnn/faster_rcnn_1_10_14657.pth
2021-07-08 21:48:00,201 - INFO - Performing training for atr_net_predcls_VG200
Performing training for atr_net_predcls_VG200
Traceback (most recent call last):
  File "/home/nimo/code_sgg/atr-net/main.py", line 113, in <module>
    main()
  File "/home/nimo/code_sgg/atr-net/main.py", line 110, in main
    model.train_test(cfg)
  File "/mnt/e/wsl_code/atr-net/src/models/atr_net.py", line 488, in train_test
    epochs=30 if config.use_early_stopping else 7)
  File "/mnt/e/wsl_code/atr-net/src/utils/train_test_utils.py", line 82, in train
    self._set_data_loaders()
  File "/mnt/e/wsl_code/atr-net/src/utils/train_test_utils.py", line 334, in _set_data_loaders
    self._filter_duplicate_rels, self._filter_multiple_preds)[0])
  File "/mnt/e/wsl_code/atr-net/src/utils/file_utils.py", line 31, in load_annotations
    with open(PATHS['json_path'] + dataset + '_' + _mode + '.json') as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'json_annos/VG200_sggen.json'

Process finished with exit code 1

I check json_annos dir, but I didn't find the *_sggen.json. I also check the code of prepare_data.py and ***_transformer_class.py , howevery there are not any information for **sggen.json. 

Can you help me?

Thank you very much!

**Comment by nickgkan** [comment]
Hi,

Sorry for not explaining this in the README.
To train for sggen you need the following:
1. Train for task=predcls.
2. Train faster-rcnn (task=objdet if I recall correctly).
3. Step 2 will create the json you want and you can use that to evaluate sggen using the command you originally used.

Note that sggen means that you evaluate with objects detected by faster-rcnn. Our approach here is two stage: first detects the objects, then predicts the relationships. The two stages are independently learned and that's why you need the above pipeline.

Thanks for your interest in our code! If you encounter any other difficulties ask a followup!

**Comment by Nimo1989** [comment]
Hi,
Thanks for your answer. 
So I need to use the code :
python3 main.py --dataset=VG200 --task=predcls --model=atr_net
to train the model for  sggen, right? 
Is there any set for faster-rcnn?

**Comment by Nimo1989** [comment]
Sorry, I should chechk the closed issue first. I find [this issue](https://github.com/deeplab-ai/atr-net/issues/3) same to my issue.
Thank you very much.

**Comment by nickgkan** [comment]
That's right, here are the commands for each step:

1. python3 main.py --dataset=VG200 --task=predcls --model=atr_net
2. python3 main.py --dataset=VG200 --task=objdet --model=object_detector
3. python3 main.py --dataset=VG200 --task=sggen --model=atr_net

Steps 1 and 2 will train and step 3 is only for eval.

**Comment by Nimo1989** [comment]
Thanks!

**Comment by alice-cool** [comment]
So , dear scholar,
 the third step's result is what?
![图片](https://user-images.githubusercontent.com/16870890/136315281-f27dca69-e58a-4cf8-9fb8-a88b654ac239.png)
I am curious about the final result. Because I always throw exceptions like the picture.

**Comment by alice-cool** [comment]
![图片](https://user-images.githubusercontent.com/16870890/136327613-f85be49f-e7e2-4cf7-a9fb-23fff592f525.png)
The last step need so big memory to run.

**Comment by nickgkan** [comment]
Hi @alice-cool 
If these are indeed sggen results, they're correct!
For micro-recall@50/100, I can see in my notes that it was ~21/~25 with graph constraints (first line in your results), and ~23/~28 without (third line in yours, with no constraints). Your other results look also consistent (and better than most SOTA models), although I don't have the expected numbers for them in my notes.

As for the memory consumption, I was running that on a 12GB gpu (RTX 2080) with batch size 1.

**Comment by alice-cool** [comment]
> 
> 
> Hi @alice-cool If there are indeed sggen results, they're correct! For micro-recall@50/100, I can see in my notes that it was ~21/~25 with graph constraints (first line in your results), and ~23/~28 without (third line in your constraints). Your other results look also consistent (and better than most SOTA models), although I don't have the expected numbers for them.
> 
> As for the memory consumption, I was running that on a 12GB gpu (RTX 2080) with batch size 1.

Thanks for your timely reply. The results is the reproduction from your code. So I think what you said is that,  "the result I showed is consistent with your expectations". 
Thank you again for your reply.
