### ISSUE TITLE
Query regarding file_utils.py

### ISSUE THREAD

**Issue by akibzaman** [deeplab-ai/atr-net#8]
Hello.

Where we are getting this _anno_ dictionary in file_utils.py? I am a bit confused about the use here.
![Screenshot from 2022-10-21 19-09-05](https://user-images.githubusercontent.com/55422467/197203411-53403573-8ed8-4c3b-9c35-030e4fdfe678.png)

**Comment by akibzaman** [comment]
Checked Again. After the preparation of data, there should be some annotations. However, my annotation is empty. is this a problem regarding the preparation of dataset? I am using VG80K.

**Comment by nickgkan** [comment]
Hi,

I suspect that some path is incorrect in the data preparation but the code handles it and creates an empty list of annotations. If you run "python prepare_data.py VG80K" as is it should build the correct annotations.

**Comment by akibzaman** [comment]
Indeed that was the problem and solved it. Thanks.
